In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

#@matplotlib inline

#data training
x=np.array([5,15,25,35,45,55]).reshape((-1,1))
y=np.array([5,20,14,32,22,38])

print(x)
print(y)

model = LinearRegression()
model.fit(x,y)

#Step 1 buat Linear regression via SCIPY
LinearRegression(copy_X=True, 
                 fit_intercept=True,
                 n_jobs=None, 
                 normalize=False)


#Step 2 hitung dan hitung coefficient of determination

model= LinearRegression().fit(x,y)
r_sq = model.score(x,y)
print('coefficient of determination',r_sq)
print('intercept:', model.intercept_)
print('slope:', model.coef_)

#0.7158756137479542


#experiment calculate new model with new input

new_model = LinearRegression().fit(x,y.reshape(-1,1))
print('intercept', new_model.intercept_)
print('slope:', new_model.coef_)

y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')



[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]
coefficient of determination 0.7158756137479542
intercept: 5.633333333333329
slope: [0.54]
intercept [5.63333333]
slope: [[0.54]]
predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
