In [ ]:
#UNSUPERVISED LEARNING : Dimensionality Reduction dan CLustering

In [ ]:
#PCA : mereduksi feature / input yang tidak relevan

import pandas as pd

weather = ['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
temp_in_01PM = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
temp_in_02PM = ['Hot','Cool','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Hot','Mild','Mild','Hot','Mild']
temp_in_03PM = ['Hot','Hot','Hot','Mild','Cool','Hot','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
temp_in_04PM = ['Hot','Cool','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
temp_in_05PM = ['Hot','Hot','Cool','Mild','Cool','Cool','Cool','Mild','Cool','Hot', 'Mild','Mild','Hot','Mild']
temp_in_06PM = ['Hot','Hot','Cool','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Cool','Mild','Hot','Mild']
temp_in_07PM = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Cool','Cool','Mild','Mild','Cool','Hot','Mild']
temp_in_08PM = ['Hot','Hot','Hot','Cool','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']


play = ['No','No','Yes','Yes','Yes',
        'No','Yes','No','Yes','Yes',
        'Yes','Yes','Yes','No']


from sklearn import preprocessing

encode = preprocessing.LabelEncoder()
weather_encoded=encode.fit_transform(weather)
#Sunny = 2 , Overcast = 0 , Rainy = 1
print(weather_encoded)

#Mild = 2 , Hot = 1, Cool = 0
temp_in_01PM_encoded = encode.fit_transform(temp_in_01PM)
print(temp_in_01PM_encoded)

#Mild = 2 , Hot = 1, Cool = 0
temp_in_02PM_encoded = encode.fit_transform(temp_in_02PM)
print(temp_in_02PM_encoded)


#Mild = 2 , Hot = 1, Cool = 0
temp_in_03PM_encoded = encode.fit_transform(temp_in_03PM)
print(temp_in_03PM_encoded)

#Mild = 2 , Hot = 1, Cool = 0
temp_in_04PM_encoded = encode.fit_transform(temp_in_04PM)
print(temp_in_04PM_encoded)


#Mild = 2 , Hot = 1, Cool = 0
temp_in_05PM_encoded = encode.fit_transform(temp_in_05PM)
print(temp_in_05PM_encoded)

#Mild = 2 , Hot = 1, Cool = 0
temp_in_06PM_encoded = encode.fit_transform(temp_in_06PM)
print(temp_in_06PM_encoded)

#Mild = 2 , Hot = 1, Cool = 0
temp_in_07PM_encoded = encode.fit_transform(temp_in_07PM)
print(temp_in_07PM_encoded)

#Mild = 2 , Hot = 1, Cool = 0
temp_in_08PM_encoded = encode.fit_transform(temp_in_08PM)
print(temp_in_08PM_encoded)

#No = 0, Yes = 1
play_encoded = encode.fit_transform(play)
label = play_encoded
print(play_encoded)

#zip encoder 
features = list(zip(weather_encoded,
                    temp_in_01PM_encoded,
                    temp_in_02PM_encoded,
                    temp_in_03PM_encoded,
                    temp_in_04PM_encoded,
                    temp_in_05PM_encoded,
                    temp_in_06PM_encoded,
                    temp_in_07PM_encoded,
                    temp_in_08PM_encoded))
print(features)




[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[1 0 1 2 0 0 0 2 0 1 2 2 1 2]
[1 1 1 2 0 1 0 2 0 2 2 2 1 2]
[1 0 1 2 0 0 0 2 0 2 2 2 1 2]
[1 1 0 2 0 0 0 2 0 1 2 2 1 2]
[1 1 0 2 0 0 0 2 0 2 0 2 1 2]
[1 1 1 2 0 0 0 0 0 2 2 0 1 2]
[1 1 1 0 0 0 0 2 0 2 2 2 1 2]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]
[(2, 1, 1, 1, 1, 1, 1, 1, 1), (2, 1, 0, 1, 0, 1, 1, 1, 1), (0, 1, 1, 1, 1, 0, 0, 1, 1), (1, 2, 2, 2, 2, 2, 2, 2, 0), (1, 0, 0, 0, 0, 0, 0, 0, 0), (1, 0, 0, 1, 0, 0, 0, 0, 0), (0, 0, 0, 0, 0, 0, 0, 0, 0), (2, 2, 2, 2, 2, 2, 2, 0, 2), (2, 0, 0, 0, 0, 0, 0, 0, 0), (1, 2, 1, 2, 2, 1, 2, 2, 2), (2, 2, 2, 2, 2, 2, 0, 2, 2), (0, 2, 2, 2, 2, 2, 2, 0, 2), (0, 1, 1, 1, 1, 1, 1, 1, 1), (1, 2, 2, 2, 2, 2, 2, 2, 2)]


In [ ]:
from sklearn.decomposition import PCA

X = features
y = label

pca_play = PCA(n_components =  1)
principalComponents_play = pca_play.fit_transform(X)

principalComponents_DF_1 = pd.DataFrame(data=principalComponents_play,columns=['TheMostRelevantOne',])

print(principalComponents_DF_1)

print(f"""Explained variation per principalComponents {pca_play.explained_variance_ratio_} 

which means the most releavant one variable contain {100* pca_play.explained_variance_ratio_[0]}% 

""" )

    TheMostRelevantOne
0             0.065792
1             0.842619
2             0.850107
3            -2.050836
4             2.905589
5             2.555860
6             2.942144
7            -2.237685
8             2.869034
9            -1.955191
10           -2.060865
11           -2.164575
12            0.138902
13           -2.700895
Explained variation per principalComponents [0.70657172] 

which means the most releavant one variable contain 70.65717158931567% 




In [ ]:
pca_play = PCA(n_components =  2)
principalComponents_play = pca_play.fit_transform(X)

principalComponents_DF_2 = pd.DataFrame(data=principalComponents_play,columns=['TheMostRelevant','TheSecondMostRelevant'])

print(principalComponents_DF_2)

print(f"""Explained variation per principalComponents {pca_play.explained_variance_ratio_} 

which means 2 most relevant variable contain {100* ( pca_play.explained_variance_ratio_[0] + pca_play.explained_variance_ratio_[1])}% 

""" )

    TheMostRelevant  TheSecondMostRelevant
0          0.065792              -0.906935
1          0.842619              -1.135367
2          0.850107               0.956464
3         -2.050836               0.125074
4          2.905589               0.015267
5          2.555860               0.014280
6          2.942144               0.963370
7         -2.237685              -0.475335
8          2.869034              -0.932837
9         -1.955191               0.067397
10        -2.060865              -1.168594
11        -2.164575               1.420872
12         0.138902               0.989272
13        -2.700895               0.067070
Explained variation per principalComponents [0.70657172 0.10656813] 

which means 2 most relevant variable contain 81.3139843701494% 




In [ ]:
#Decision Tree
#Library yang perlu diingat
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

X = principalComponents_DF_1
y = label

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.5, random_state=1)

model = DecisionTreeClassifier()
model = model.fit(X_train,y_train)
y_pred = model.predict(X_test)

print(f"""
____________________________________________________________

Berdasarkan model Decision Tree kita ()

Prediksi Machine Learning Decision Tree dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

{model.predict([[0.1]])} <- Not Play      (Overcast, dan Suhu Mild)
{model.predict([[0.1]])} <- Not Play      (Overcast, dan Suhu Hot)
{model.predict([[0.1]])} <- Not Play      (Rainy, dan Suhu Hot)
{model.predict([[0.1]])} <- Not Play      (Rainy, dan Suhu Mild)

____________________________________________________________

""")


____________________________________________________________

Berdasarkan model Decision Tree kita ()

Prediksi Machine Learning Decision Tree dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

[0] <- Not Play      (Overcast, dan Suhu Mild)
[0] <- Not Play      (Overcast, dan Suhu Hot)
[0] <- Not Play      (Rainy, dan Suhu Hot)
[0] <- Not Play      (Rainy, dan Suhu Mild)

____________________________________________________________




/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
#Decision Tree
#Library yang perlu diingat
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

X = principalComponents_DF_2
y = label

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.5, random_state=1)

model = DecisionTreeClassifier()
model = model.fit(X_train,y_train)
y_pred = model.predict(X_test)

print(f"""
____________________________________________________________

Berdasarkan model Decision Tree kita ()

Prediksi Machine Learning Decision Tree dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No


{model.predict([[0,2]])} <- Play      (Overcast, dan Suhu Mild)
{model.predict([[0,2]])} <- Play      (Overcast, dan Suhu Hot)
{model.predict([[0,2]])} <- Play      (Rainy, dan Suhu Hot)
{model.predict([[0,2]])} <- Play      (Rainy, dan Suhu Mild)

____________________________________________________________

""")


____________________________________________________________

Berdasarkan model Decision Tree kita ()

Prediksi Machine Learning Decision Tree dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No


[1] <- Play      (Overcast, dan Suhu Mild)
[1] <- Play      (Overcast, dan Suhu Hot)
[1] <- Play      (Rainy, dan Suhu Hot)
[1] <- Play      (Rainy, dan Suhu Mild)

____________________________________________________________




/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
import pickle

pickle.dump(model,open('model_classifier_terbaik.pkl','wb'))

model_load = pickle.load(open('model_classifier_terbaik.pkl','rb'))

print(f"""
____________________________________________________________

Berdasarkan model *terbaik* kita (n_estimator =100)

Prediksi Machine Learning dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

{model.predict([[0,2]])} <- Play      (Overcast, dan Suhu Mild)
{model.predict([[0,1]])} <- Play      (Overcast, dan Suhu Hot)
{model.predict([[1,1]])} <- Not Play  (Rainy, dan Suhu Hot)
{model.predict([[1,2]])} <- Not Play  (Rainy, dan Suhu Mild)

____________________________________________________________

""")



____________________________________________________________

Berdasarkan model *terbaik* kita (n_estimator =100)

Prediksi Machine Learning dengan input 
cuaca Rainy,Overcast, dan Suhu Mild, Hot

1 = Play, 0 = No

[1] <- Play      (Overcast, dan Suhu Mild)
[1] <- Play      (Overcast, dan Suhu Hot)
[1] <- Not Play  (Rainy, dan Suhu Hot)
[1] <- Not Play  (Rainy, dan Suhu Mild)

____________________________________________________________




/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
